# Use an official .NET runtime as a parent image
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

# Build stage
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src

# Copy the Schedule.csproj file
COPY ["Schedule/Schedule.csproj", "Schedule/"]
RUN dotnet restore "Schedule/Schedule.csproj"

# Copy the rest of the files
COPY . .

# Set the working directory to /src and build the project
WORKDIR "/src"
RUN dotnet build "Schedule/Schedule.csproj" -c Release -o /app/build

# Publish stage
FROM build AS publish
RUN dotnet publish "Schedule/Schedule.csproj" -c Release -o /app/publish

# Final stage: Use the runtime image and copy the published app
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Schedule.dll"]
