# Use an official .NET runtime as a parent image
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

# Build stage
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Project-API.csproj", "./"]
RUN dotnet restore "./Project-API.csproj"
COPY . .
WORKDIR "/src"
RUN dotnet build "Project-API.csproj" -c Release -o /app/build

# Publish stage
FROM build AS publish
RUN dotnet publish "Project-API.csproj" -c Release -o /app/publish

# Final stage
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Project-API.dll"]
